---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 14/06/2021 11:22
---

function MasterTargetEnemy(self)
    local playerTargetMarkerController = PlayerTargetMarkerController:Init()
    local crowdEnemyNamePlatesController = CrowdEnemyNamePlatesController:Init()

    self:SetScript(SCRIPT_HANDLER.ON_EVENT, function(_, ...)
        playerTargetMarkerController:OnEvent(...)
        crowdEnemyNamePlatesController:OnEvent(...)
    end)
    self:RegisterEvent(EVENT.PLAYER_TARGET_CHANGED)
    self:RegisterEvent(EVENT.NAME_PLATE_UNIT_ADDED)
    self:RegisterEvent(EVENT.PLAYER_ENTER_COMBAT)
    self:RegisterEvent(EVENT.PLAYER_LEAVE_COMBAT)
    self:RegisterEvent(EVENT.COMBAT_LOG_EVENT_UNFILTERED)
end