---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 14/06/2021 11:48
---

local _Controller, _ = Class:create("PlayerTargetMarkerController")
PlayerTargetMarkerController = _Controller

function PlayerTargetMarkerController:OnEvent(event, arg1)
    if event == EVENT.PLAYER_TARGET_CHANGED then
        self:_OnPlayerTargetChanged()
        return
    end

    if event == EVENT.NAME_PLATE_UNIT_ADDED then
        self:_OnNamePlateUnitAdded(arg1)
        return
    end

    if event == EVENT.PLAYER_ENTER_COMBAT then
        self:_OnPlayerEnterCombat()
        return
    end

    if event == EVENT.PLAYER_LEAVE_COMBAT then
        self:_OnPlayerLeaveCombat()
        return
    end
end

function PlayerTargetMarkerController:_OnPlayerTargetChanged()
    if self.lastTargetNamePlate then
        self.lastTargetNamePlate.markerIcon:Hide()
    end

    if not UnitCanAttack(UNIT.PLAYER, UNIT.TARGET) then
        return
    end

    local namePlate = C_NamePlate.GetNamePlateForUnit(UNIT.TARGET)
    if namePlate then
        namePlate.markerIcon:Show()
        self.lastTargetNamePlate = namePlate
    end
end

function PlayerTargetMarkerController:_OnNamePlateUnitAdded(unit)
    local namePlate = C_NamePlate.GetNamePlateForUnit(unit)
    self:_AttachMarkIconToNamePlate(namePlate)
    namePlate.markerIcon:Hide()

    -- Show marker icon when player targeted an unit
    -- but name plate wasn't created
    if namePlate == C_NamePlate.GetNamePlateForUnit(UNIT.TARGET) then
        namePlate.markerIcon:Show()
        self.lastTargetNamePlate = namePlate
    end
end

function PlayerTargetMarkerController:_OnPlayerEnterCombat()
    local namePlate = C_NamePlate.GetNamePlateForUnit(UNIT.TARGET)
    if namePlate then
        namePlate.markerIcon:Show()
    end
end

function PlayerTargetMarkerController:_OnPlayerLeaveCombat()
    local namePlate = C_NamePlate.GetNamePlateForUnit(UNIT.TARGET)
    if namePlate then
        namePlate.markerIcon:Show()
    end
end

function PlayerTargetMarkerController:_AttachMarkIconToNamePlate(namePlate)
    if namePlate.markerIcon ~= nil then
        return
    end

    local size = namePlate.UnitFrame.healthBar:GetHeight() + 4
    local markerIcon = MarkerIcon:Init(namePlate.UnitFrame, size, { "RIGHT", namePlate, "LEFT", -2, -6 })
    namePlate.markerIcon = markerIcon
end

